### ISSUE TITLE
Issue with set-up colors creting a new platform

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#1]
When I create a platform name, address... I arrive on the page of the branding where I select a color, then all the fields I previously filled are removed, I have to fill in them again.

**Comment by Justinuz** [comment]
Fixed in dev.

**Comment by MelanieApplincourt** [comment]
Not OK, the problem is still the same ?

**Comment by MelanieApplincourt** [comment]
Pop-up appears to request the user to save : OK
