### ISSUE TITLE
Traduction issues: FR version

### ISSUE THREAD

**Issue by GuillaumeGolinvaux** [MelanieApplincourt/REPO_UZ_1234987#100]
![screenshot_2016-04-25-13-47-34 1](https://cloud.githubusercontent.com/assets/18420928/14782929/a7d3a280-0aec-11e6-939d-768ca522a133.jpg)

In delivery preparation in driver app:
1) Put a space between 0sans préparation and 0 non dispatché
2) 0 su 15 parcels prepared: changer vers 0 sur 15 colis préparés
3) Pickup: translate to "Collecte:"

![image](https://cloud.githubusercontent.com/assets/18420928/14783452/fe14e2e6-0aef-11e6-92f3-8b1887f14c8a.png)

1) Change "to be delivered" to "en attente de livraison" (delivery details for driver app)

![image](https://cloud.githubusercontent.com/assets/18420928/14783620/245374b2-0af1-11e6-91e6-bfbe3fd17388.png)

1) Change the "Cancel" button to "Annuler" (delivery failed option for driver app)

![screenshot_2016-04-25-14-29-11 1](https://cloud.githubusercontent.com/assets/18420928/14783763/2958e112-0af2-11e6-9af5-c90401cbb842.jpg)

In the delivery failed screen, when selecting the reason of the failed delivery, the reasons in the list are not translated to french.

**Comment by icedfox** [comment]
Il y a un bug avec togettext et la maj des traductions, to investigate

**Comment by GuillaumeGolinvaux** [comment]
Still to be translated:
![screenshot_2016-05-13-11-53-06 1](https://cloud.githubusercontent.com/assets/18420928/15244459/963a1964-1901-11e6-9b7a-fdb24efa6684.jpg)
On the bottom of the screen, it is written "Deliver Parcel". Translate to "Livrer Colis"
![screenshot_2016-05-13-11-57-03 1](https://cloud.githubusercontent.com/assets/18420928/15244525/d64e1c62-1901-11e6-9963-bdb43d5728e1.jpg)
The list of reasons for non-delivering is still in english

**Comment by GuillaumeGolinvaux** [comment]
On the Dispatcher App (Fr):
![screenshot_2016-05-13-12-09-28 1](https://cloud.githubusercontent.com/assets/18420928/15244998/5bd12e2c-1904-11e6-88cc-b17e3b3368de.jpg)
The text on the bottom half of the screen is not translated

**Comment by icedfox** [comment]
Les raisons pour la non livraison devraient êtres traduites maintenant...

**Comment by GuillaumeGolinvaux** [comment]
OK!
