### ISSUE TITLE
Edition of round, dispatcher app, add parcel but parcel could not be found

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#105]
Regression test for today, dispatcher = dispatcher1.demo@urbantz.com, I go to the dispatcher app, take a round and try to add an orphan parcel: 1330221000010
This parcel cannot be found where as it is in the application.

**Comment by Justinuz** [comment]
I tried to add the same parcel in round 'R01' with this dispatcher. The parcel is correctly added at the end of the list.
![capture d ecran 2016-04-27 a 10 05 00](https://cloud.githubusercontent.com/assets/18256571/14845632/c21950d0-0c5f-11e6-83d8-b5089f8e4a6e.png)

**Comment by MelanieApplincourt** [comment]
Si ça marche pour vous c'est bon pour moi ;-)
