### ISSUE TITLE
Create a parcel pick-up filled in by default

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#108]
I create a new parcel with delivery only (I let the pick-up selection deactivated) but on save a pick-up date has been set-up by default. I should see no pick-up date.
![screen shot 2016-04-27 at 08 09 09](https://cloud.githubusercontent.com/assets/2649355/14843326/84d65976-0c4f-11e6-8b1c-0bc35a9ceee7.png)

**Comment by Justinuz** [comment]
Done

**Comment by MelanieApplincourt** [comment]
OK
