### ISSUE TITLE
Add fields in the parcels and status export

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#11]
Add the fields:
- Client
- Customer Reference
- Air Waybill
- Company
- Contact
- Non delivery reason
- Delivery comments
- Export date
- Flux name

**Comment by MelanieApplincourt** [comment]
Just 2 remarks:
- [x] it would have been nice to have a different name for the files (status vs. history)
- [x] There is a column in duplicate: reason for non delivery

**Comment by MelanieApplincourt** [comment]
Weight and volume does not seem to be filled in correctly (empty)

**Comment by Jon79** [comment]
Add First Mile fields in the export

**Comment by MelanieApplincourt** [comment]
Magnifique !!!!
