### ISSUE TITLE
Adding a driver in a flow does not work anytime

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#110]
Sometimes when I try to add a driver in a flow, I cannot see the selection list of the driver name & vehicle.
I've notice that when I open the console, it works ...
![screen shot 2016-04-27 at 09 21 48](https://cloud.githubusercontent.com/assets/2649355/14846010/d7f97c34-0c61-11e6-9e5c-c5033a91e135.png)

**Comment by Justinuz** [comment]
I can't reproduce the bug.

**Comment by Jon79** [comment]
To be tested in DEV

**Comment by GuillaumeGolinvaux** [comment]
Ok!
Now all drivers are displayed and the PM can chose which one to use by selecting the vehicle type.
![image](https://cloud.githubusercontent.com/assets/18420928/15357291/29dda0f0-1cfe-11e6-8d9f-c9d967ae6c0a.png)
