### ISSUE TITLE
Adresse exception management, when go to a not geocoded address, do not show the map of the previous address

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#112]
When I confirm an address, i automatically go to te next one. If the next one is not geocoded, the map of the previous address is displayed, it should be empty:
![screen shot 2016-04-27 at 12 42 36](https://cloud.githubusercontent.com/assets/2649355/14849868/b810d098-0c75-11e6-9975-bd4357044798.png)

**Comment by Justinuz** [comment]
Done

**Comment by MelanieApplincourt** [comment]
OK Mario !
