### ISSUE TITLE
Spelling mistake (error message round editor FR)

### ISSUE THREAD

**Issue by GuillaumeGolinvaux** [MelanieApplincourt/REPO_UZ_1234987#113]
![image](https://cloud.githubusercontent.com/assets/18420928/14855616/02bd2cf8-0c95-11e6-8b6a-c24550fae078.png)
For the error message in the Round Editor FR the message is 
"Erreur: Edition échoué 
Les tournées ne peuvent pas être sauvés".
Change to 
"Erreur: Edition échouée
Les tournées ne peuvent pas être sauvées"

**Comment by Justinuz** [comment]
DONE

**Comment by GuillaumeGolinvaux** [comment]
Ok!
