### ISSUE TITLE
Round Editor: Pickup & Delivery separated

### ISSUE THREAD

**Issue by GuillaumeGolinvaux** [MelanieApplincourt/REPO_UZ_1234987#114]
In the example, the pacel ID 440000033377 was initially picked up and delivered in R01. However, I could change the pickup to R02 and leave the delivery in R01 without error or alert message. It should be clear to the Platform Manager that he is creating an operational error on the field.
![image](https://cloud.githubusercontent.com/assets/18420928/14856100/0a1bd51a-0c97-11e6-83ef-2f434457dc8c.png)
![image](https://cloud.githubusercontent.com/assets/18420928/14856109/16c1e30e-0c97-11e6-9523-ce4a42e64b18.png)

**Comment by Justinuz** [comment]
Done

**Comment by GuillaumeGolinvaux** [comment]
OK: cannot move independently pickups & deliveries from the same round.
![image](https://cloud.githubusercontent.com/assets/18420928/15248104/9e575e1a-1918-11e6-8912-3727db305352.png)
