### ISSUE TITLE
Translation issue: round editor warning message

### ISSUE THREAD

**Issue by GuillaumeGolinvaux** [MelanieApplincourt/REPO_UZ_1234987#116]
![image](https://cloud.githubusercontent.com/assets/18420928/14879299/a1de7448-0d28-11e6-9c75-2fef3f9cf7f9.png)

The error message for partially optimized and empty round optimization in the round editor are not translated to french.

**Comment by Justinuz** [comment]
DONE

**Comment by GuillaumeGolinvaux** [comment]
Ok!
