### ISSUE TITLE
A flow cannot be deleted

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#121]

**Comment by Jon79** [comment]
To be tested in DEV

**Comment by GuillaumeGolinvaux** [comment]
When I create a flux and delete it, I get the popup: "are you sure..."

When selecting Cancel, I get the grey scree below:
![image](https://cloud.githubusercontent.com/assets/18420928/15188029/03bf1052-17a4-11e6-849b-ba3fba15db29.png)

Nothing happens and the only way to get back is by pressing the Back Button of the browser.

The same error can be seen when clicking on "Accept". Although the action of deleting the flu is indeed taken.

**Comment by GuillaumeGolinvaux** [comment]
Ok.
