### ISSUE TITLE
In the default design the selection of address in the exception is not clear

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#124]
When selected, an address appears in dark grey, which is not clear visually:
![screen shot 2016-04-29 at 09 41 14](https://cloud.githubusercontent.com/assets/2649355/14911633/e2fde926-0df6-11e6-8706-ac5adb179057.png)

**Comment by ventur** [comment]
I don't know who did it, but it is already donde. 
<img width="697" alt="screen shot 2016-05-26 at 13 58 58" src="https://cloud.githubusercontent.com/assets/609359/15573837/0cbcbf9a-234a-11e6-9cc2-d79ea10cdc78.png">

**Comment by Justinuz** [comment]
This is not ok. If you select the default theme and then select another: 
![capture d ecran 2016-06-01 a 14 31 02](https://cloud.githubusercontent.com/assets/18256571/15709530/861c33a6-2805-11e6-84ee-d6e21108d08d.png)
