### ISSUE TITLE
Announcement: Cannot change the month in search criteria

### ISSUE THREAD

**Issue by GuillaumeGolinvaux** [MelanieApplincourt/REPO_UZ_1234987#125]
![image](https://cloud.githubusercontent.com/assets/18420928/14913291/4b031888-0e02-11e6-94f0-0e2eae6bf8e8.png)

On the 29/04, I imported parcels for the 03/05. When I go in the Parcels Tab, I cannot change the month I am looking at in the date settings.
Same goes for the Rounds and the Dashboard Tabs.

**Comment by Jon79** [comment]
Try to scroll
