### ISSUE TITLE
The statistique seems to be wrong

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#129]
The number of parcel graph is strange, we have rounds created but no parcels for the same period ?
![screen shot 2016-04-29 at 14 59 43](https://cloud.githubusercontent.com/assets/2649355/14916651/286395e6-0e1b-11e6-9e69-8b979e0158e2.png)

**Comment by Jon79** [comment]
C'est bien possible, vu qu'on efface des colis de temps en temps...

On 29 April 2016 at 15:01, MelanieApplincourt notifications@github.com
wrote:

> The number of parcel graph is strange, we have rounds created but no
> parcels for the same period ?
> [image: screen shot 2016-04-29 at 14 59 43]
> https://cloud.githubusercontent.com/assets/2649355/14916651/286395e6-0e1b-11e6-9e69-8b979e0158e2.png
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/MelanieApplincourt/REPO_UZ_1234987/issues/129

## 

_Jonathan Weber_
togetair
Co-founder & CTO
www.togetair.com
+32 477 981097

**Comment by Justinuz** [comment]
The schema of stats changed with first mile. We need to clear the collections and regenerate all the stats.

**Comment by MelanieApplincourt** [comment]
Could you check if this data are correct: stats i test for platform regression test / may. I can see a lot of rounds created in may but no rounds appears on the graph, is it normal ?

![screen shot 2016-04-30 at 15 57 51](https://cloud.githubusercontent.com/assets/2649355/14936420/7a0124be-0eec-11e6-9307-f9c55c1fcf65.png)

**Comment by Justinuz** [comment]
Done

**Comment by MelanieApplincourt** [comment]
OK
