### ISSUE TITLE
Add language in the user registration

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#13]
After user created, clicking on the link to register, the user can no more set his language.

Language to be added.

**Comment by Jon79** [comment]
The user can select the language on the top-left of the screen. It is assumed that the language of the interface is his preferred language. Furthermore, the interface will be adapted in the language he has chosen in his profile, another reason to link interface and user profile language. By default the language chosen is the one of the user's browser.

**Comment by MelanieApplincourt** [comment]
OK, nothing to do.
