### ISSUE TITLE
Fix iOs mess...

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#130]
- [x] Fix login error after login
- [x] Fix scan QR code
- [x] Font not correct
- [x] On log-in, allow the user to use the "access"

**Comment by icedfox** [comment]
La police qui ne s'affiche pas correctement est reproduit seulement en Prod et sur iOS.

**Comment by icedfox** [comment]
Tried accessing the bucket directly on iPhone (safari mobile) and the fonts loaded properly.

**Comment by MelanieApplincourt** [comment]
OK :-)
