### ISSUE TITLE
Save geocode in parcel log when delivering

### ISSUE THREAD

**Issue by Jon79** [MelanieApplincourt/REPO_UZ_1234987#132]

**Comment by icedfox** [comment]
Get coordinates when the driver performs an action on the parcel delivery dialog (success or failure, track where it happened)

**Comment by icedfox** [comment]
Changed the TrackingService to add a method to get the current position.
If getting the current position fails, we send the last position.
If there's no last position, return an error (resolve null for now)

Waiting to know if this will be a requirement or not

**Comment by icedfox** [comment]
No requirement for the moment, and fixed the server-side saving of the coords

**Comment by GuillaumeGolinvaux** [comment]
Revu avec Gael: ok!
