### ISSUE TITLE
For rounds with pick-up the score of the driver is not correct

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#134]
![screen shot 2016-04-30 at 21 19 48](https://cloud.githubusercontent.com/assets/2649355/14938082/5c47effc-0f19-11e6-9c66-9a8898177af4.png)

**Comment by Jon79** [comment]
Bien trouvé ;)
Le 30 avr. 2016 21:20, "MelanieApplincourt" notifications@github.com a
écrit :

**Comment by MelanieApplincourt** [comment]
OK
