### ISSUE TITLE
Driver app: deliver from the parcels list does not work properly

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#138]
The first time I arrive on the list I can click on the button to deliver, it works, but the next time I have to click 2 tiles to arrive on the delivery screen.
When I arrive on the signature screen from the parcel list I have to click 2 times to confirm the delivery.

**Comment by icedfox** [comment]
Modal over modal problem, check workaround

**Comment by MelanieApplincourt** [comment]
OK
