### ISSUE TITLE
As a user of the app, in the app I can update my language and photo

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#140]
On click on the picture in the menu, I can access a page where I can update my language and my picture. On save this must be changed on my profile.

**Comment by icedfox** [comment]
Il reste un peu de styling a faire, mais c'est fait

**Comment by GuillaumeGolinvaux** [comment]
Données mises à jour via l'application! (Driver1@uz.com)
