### ISSUE TITLE
Improve calculation of the timings of the point to point and get more realistic rounds

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#141]
The rounds are too optimistic at the moment and not feasible in the timing given by ESRI. This should be improved.
It should also be possible to calculate the route specifically for bikes or vans vehicle types. 
- [ ] Check and test in Esri if we could send new parameters to get a more realistic timing
- [ ] Adapt the timing calculation to the vehicle type: bike or motor vehicle: Esri by sending new data or google ?
- [ ] Improve the management of "non reachable" parcels
- Ensure to have traffic stats everywhere in the world

**Comment by ventur** [comment]
In the flux, on announcement configuration, it is possible to enable or disable traffic data and also to set a containment margin for the time window
