### ISSUE TITLE
As an admin I can copy a platform from sandbox to prod

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#143]

**Comment by GuillaumeGolinvaux** [comment]
When I import a Vehicle Type, a Hub or a Flux, I receive the popup message saying that it was successfully created, but it is actually not created:

In that order:
![image](https://cloud.githubusercontent.com/assets/18420928/15706311/3e8acb22-27f3-11e6-947b-bf8f1e3f0609.png)

![image](https://cloud.githubusercontent.com/assets/18420928/15706321/4ddfead0-27f3-11e6-8a71-065f7460a9cb.png)

![image](https://cloud.githubusercontent.com/assets/18420928/15706334/6161de60-27f3-11e6-820c-2efdae67dd4b.png)

In the import of the Flux, the time windows of the announcement are not imported:
![image](https://cloud.githubusercontent.com/assets/18420928/15706469/08749e68-27f4-11e6-9454-7c5a612219c1.png)
