### ISSUE TITLE
Improve geocoding of addresses

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#147]
Geocode addresses in London for instance

**Comment by ventur** [comment]
Included the option to choose google for geocoding

**Comment by MelanieApplincourt** [comment]
Wouldn't we also adapt the proposition in the exception management, it seems that is is base on esri even when I select google geocoding ?

**Comment by Jon79** [comment]
No there its always google
Le 10 mai 2016 20:20, "MelanieApplincourt" notifications@github.com a
écrit :

**Comment by GuillaumeGolinvaux** [comment]
Ok
