### ISSUE TITLE
As a PM I can print the route sheet of rounds

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#148]
As a platform manager, in the dashboard I can click on a button to print the route sheets of my rounds. 
I can select all the rounds or a specific rounds (like when printing barcodes).

The round sheet is the list of all parcels to be delivered or picked-up in a round with 1 line = 1 action. The list is sorted by sequence. info to be displayed is:
- Sequence
- Recipient name
- Recipient address
- Time slots
- Client & customer reference (if any)
- Recipient signature (empty cell)

This document must be printed in landscape.

**Comment by MelanieApplincourt** [comment]
I expect the sheet to be in landscape with more parcels on 1 page (15 at least).

**Comment by ventur** [comment]
How I already developed the list view, I left it and now the user can decide to print as list or as table (table by default)

**Comment by GuillaumeGolinvaux** [comment]
Ok
