### ISSUE TITLE
In a flow / list of drivers cannot be edited

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#149]
Platform Ecolotrans (First one) / Ecolotrans test optim:
When I go to the driver list I cannot see the vehicle selected and I cannot add neither delete a driver.

**Comment by MelanieApplincourt** [comment]
sometimes, for a driver with a vehicle, when I come back on the driver page (in a flow), this dirver appear with the field vehicle empty:
![screen shot 2016-05-18 at 09 29 27](https://cloud.githubusercontent.com/assets/2649355/15350973/ee47e08a-1cdc-11e6-817c-2761e27ce37c.png)

**Comment by GuillaumeGolinvaux** [comment]
In the Driver Tab (Flow configuration) **the first time we open the Tab**, the drivers with vehicles have a blank field:

![image](https://cloud.githubusercontent.com/assets/18420928/15353482/9b54b8d2-1ce9-11e6-86a5-fc3beb8b52f0.png)

However, when refreshing the page, the field show the vehicles:

![image](https://cloud.githubusercontent.com/assets/18420928/15353514/c023e4e4-1ce9-11e6-8b49-231710a7edc6.png)

**Comment by GuillaumeGolinvaux** [comment]
Ok
