### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#16]
In the settings / hub / notifications, the notifications activation text is not translated in french (see print screen)
![screen shot 2016-04-05 at 14 06 27](https://cloud.githubusercontent.com/assets/2649355/14281169/bcba6004-fb37-11e5-8919-ab5314702705.png)

In the settings / flow / announcement, the selection of the optim to be launch manually or automatically, the manually / automatically should be translated in french

**Comment by Justinuz** [comment]
DONE :)

**Comment by MelanieApplincourt** [comment]
This translation is still not correct:
In the settings / flow / announcement, the selection of the optim to be launch manually or automatically, the manually / automatically should be translated in french

**Comment by Justinuz** [comment]
Done :+1:

**Comment by MelanieApplincourt** [comment]
OK
