### ISSUE TITLE
When I arrive on the web app, no platform name appears

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#161]
On login, the default platform name does not appear
![screen shot 2016-05-17 at 19 43 00](https://cloud.githubusercontent.com/assets/2649355/15334004/71eb3174-1c6c-11e6-9abf-f4c337d7628c.png)
:

**Comment by ventur** [comment]
I can't reproduce, I tried with melanie@urbantz.com, admin@uz.com and ventura.dani@gmail.com, cleaning the cache, opening in a private mode... but I always have the platform selected.

**Comment by MelanieApplincourt** [comment]
OK I close...
