### ISSUE TITLE
Manage flow without optim where sequence is not always filled-in

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#165]
In the case the announcer import data in a flow without optimisation and the sequence in provided but some of them are empty:
- Have an option in the flow / announcement only without optimisation where we can select : How to manage the tasks without sequence: Add at the end OR recalculate the optimised sequence for the whole round.
- When the option "at the end" is set, the parcels without sequence should be added in the right order (optimised) but the initial sequence provided must be respected and remain unchanged.

**Comment by Justinuz** [comment]
DONE :metal:

**Comment by ventur** [comment]
Fix small bug for not duplicate the sequence

**Comment by MelanieApplincourt** [comment]
I tested but it does not seem to work... I used the platform TGL, flow S&V Varlin Triporteur.
I have a message "There are no vehicles that matches the parcel requirements."

**Comment by Justinuz** [comment]
Fixed

**Comment by GuillaumeGolinvaux** [comment]
Ok
