### ISSUE TITLE
export fine tuning

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#166]
The date format of the status change must be:
jj/mm/aaaa hh:nn:ss
no T and Z should appear

**Comment by GuillaumeGolinvaux** [comment]
[export-history-2016-06-05 (2).xlsx](https://github.com/MelanieApplincourt/REPO_UZ_1234987/files/270537/export-history-2016-06-05.2.xlsx)
In the File, the forelast collumn has no title and you can see T's and Z's in the format.
(tested on http://test.web.urbantz.com.s3-website-eu-west-1.amazonaws.com/)

**Comment by GuillaumeGolinvaux** [comment]
Perfect!
