### ISSUE TITLE
Settings / fleet I have a wrong warning pending changes 

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#167]
When I move from one vehicle type to another I can see the warning that I have pending changes but no changes have been done:
![screen shot 2016-05-18 at 09 40 50](https://cloud.githubusercontent.com/assets/2649355/15351015/2c6bf7de-1cdd-11e6-9052-255e6ecec06c.png)

**Comment by Justinuz** [comment]
Done

**Comment by GuillaumeGolinvaux** [comment]
Ok!
Works on http://test.web.urbantz.com.s3-website-eu-west-1.amazonaws.com/
