### ISSUE TITLE
In Sandbox (Prod): error in round time calculation

### ISSUE THREAD

**Issue by GuillaumeGolinvaux** [MelanieApplincourt/REPO_UZ_1234987#178]
![image](https://cloud.githubusercontent.com/assets/18420928/15428217/517a316c-1e9a-11e6-856c-cc48e1f5c5d8.png)
As we can see in the screenshot, the total time is not equal to the sum of the service time and the travel time

**Comment by ventur** [comment]
It is not a bug, we show the duration that is equal to Travel Time + Service Time + Wait Time (that is not shown in the interface)

**Comment by GuillaumeGolinvaux** [comment]
Ok
