### ISSUE TITLE
Rouds / The total of rounds duration is wrong

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#18]
![screen shot 2016-04-06 at 10 16 07](https://cloud.githubusercontent.com/assets/2649355/14310151/c417fb8c-fbe0-11e5-839c-7ba92703c3c0.png)

**Comment by Justinuz** [comment]
DONE :)

**Comment by MelanieApplincourt** [comment]
OK tested
