### ISSUE TITLE
Sometimes the wait gps signal loading screen is running non-stop on the parcel delivery screen

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#181]
Click on pick-up or delivery
![screenshot_20160522-153938](https://cloud.githubusercontent.com/assets/2649355/15454259/be0e4580-2033-11e6-81cf-6ccf79cb2a7e.png)
Then, validate to confirm with signature
![screenshot_20160522-154000](https://cloud.githubusercontent.com/assets/2649355/15454261/df4b1336-2033-11e6-9580-c0a9204a95d5.png)
Then go back. At this moment the loading for GPS appears and never stops. Then I have the same each time I click to deliver or pick-up a parcel.
![screenshot_20160522-154007](https://cloud.githubusercontent.com/assets/2649355/15454263/f6d147d2-2033-11e6-9742-d20b436eb861.png)

**Comment by MelanieApplincourt** [comment]
Click on pick-up or delivery
![screenshot_20160522-153938](https://cloud.githubusercontent.com/assets/2649355/15454259/be0e4580-2033-11e6-81cf-6ccf79cb2a7e.png)
Then, validate to confirm with signature
![screenshot_20160522-154000](https://cloud.githubusercontent.com/assets/2649355/15454261/df4b1336-2033-11e6-9580-c0a9204a95d5.png)
Then go back. At this moment the loading for GPS appears and never stops. Then I have the same each time I click to deliver or pick-up a parcel.
![screenshot_20160522-154007](https://cloud.githubusercontent.com/assets/2649355/15454263/f6d147d2-2033-11e6-9742-d20b436eb861.png)

**Comment by icedfox** [comment]
The back button only hid the dialog.
Changed to reject the promise thus resulting in a delivery failure

**Comment by MelanieApplincourt** [comment]
OK
