### ISSUE TITLE
The Hub map with all rounds cannot be displayed anymore

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#19]
![screen shot 2016-04-06 at 12 29 16](https://cloud.githubusercontent.com/assets/2649355/14313679/34d6605e-fbf3-11e5-9e50-b0be5a5ad80b.png)

**Comment by Jon79** [comment]
Done

**Comment by MelanieApplincourt** [comment]
OK
