### ISSUE TITLE
Issue adding drivers in a flow

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#195]
In the driver tab of a flow, I add a driver (no driver encoded previously), the I click on the "+" to add an additional driver and then the previous driver I encoded is removed:
![screen shot 2016-05-25 at 08 42 50](https://cloud.githubusercontent.com/assets/2649355/15530486/e79f7aa4-2254-11e6-932d-500e6c945b50.png)
![screen shot 2016-05-25 at 08 42 55](https://cloud.githubusercontent.com/assets/2649355/15530488/e934303a-2254-11e6-899c-871d2757ab04.png)

**Comment by Justinuz** [comment]
Done :dancer:
