### ISSUE TITLE
I cannot add a new flow

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#196]
The message should be more specific, at the moment I have: error, the record could not be created...

![screen shot 2016-05-25 at 08 51 21](https://cloud.githubusercontent.com/assets/2649355/15530637/e5110c8e-2255-11e6-9c0b-605a8c7fd5f7.png)

**Comment by Justinuz** [comment]
DONE :scream_cat:
