### ISSUE TITLE
As PM I can input coordinates (latitude, longitude)

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#205]
Add the coordinates int he mapping
Ensure if the coordinates are filled in, do not send then to geocoding

[Testdata_TH_Urbantz_20160530 with geoco.xlsx](https://github.com/MelanieApplincourt/REPO_UZ_1234987/files/290521/Testdata_TH_Urbantz_20160530.with.geoco.xlsx)

**Comment by GuillaumeGolinvaux** [comment]
I cannot import the announcement file (no error message popup, but an error in the logs)

![image](https://cloud.githubusercontent.com/assets/18420928/15709038/b58dab40-2802-11e6-9af2-ce6b33726d33.png)

[Testdata_TH_Urbantz_20160530.with.geoco.xlsx](https://github.com/MelanieApplincourt/REPO_UZ_1234987/files/293337/Testdata_TH_Urbantz_20160530.with.geoco.xlsx)

**Comment by GuillaumeGolinvaux** [comment]
Happy panda is happy
![image](https://cloud.githubusercontent.com/assets/18420928/15745672/5d39faee-28d3-11e6-909d-969d757bd67a.png)
