### ISSUE TITLE
A new platform cannot be created

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#206]
![screen shot 2016-05-31 at 12 12 47](https://cloud.githubusercontent.com/assets/2649355/15671059/1865cae8-2729-11e6-8289-4e6d2d008e89.png)
![screen shot 2016-05-31 at 12 12 41](https://cloud.githubusercontent.com/assets/2649355/15671061/1a35b4aa-2729-11e6-9816-6caba7b4a570.png)

**Comment by icedfox** [comment]
![screenshot from 2016-06-01 11 42 05](https://cloud.githubusercontent.com/assets/4616379/15705091/f5b8ac5c-27ed-11e6-9aee-e3a208c3557e.png)
Also can't upload a photo
