### ISSUE TITLE
New flow creation does not work properly

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#207]
- The save button is not correctly enabled
- I cannot import a file  sample to define the mapping

**Comment by MelanieApplincourt** [comment]
![screen shot 2016-05-31 at 12 21 02](https://cloud.githubusercontent.com/assets/2649355/15671324/9721ba58-272a-11e6-9afb-5f240b446bb8.png)

**Comment by icedfox** [comment]
Problem saving a flux: Dates are not saved properly:
timeWindow: {
margin : 5
start : "1970-01-01T08:00:00.000Z"
stop : "1970-01-01T10:00:00.000Z"
}
Refreshing the page and looking at the dates, we get this error

![screenshot from 2016-06-01 14 07 19](https://cloud.githubusercontent.com/assets/4616379/15708968/4b149166-2802-11e6-9e9e-582776eae3d5.png)

Also Timezone not saved

**Comment by icedfox** [comment]
Problem saving drivers:
Saving the driver:
![screenshot from 2016-06-01 15 23 47](https://cloud.githubusercontent.com/assets/4616379/15711108/f78daef0-280c-11e6-9a25-3de8efafd50f.png)

After refreshing:
![screenshot from 2016-06-01 15 24 25](https://cloud.githubusercontent.com/assets/4616379/15711111/fdb85280-280c-11e6-9125-66464ca077a1.png)

After saving 2 drivers:
![screenshot from 2016-06-01 15 25 29](https://cloud.githubusercontent.com/assets/4616379/15711156/3056dda6-280d-11e6-9c67-5c77ba1954d6.png)

After refreshing, only one remains:
![screenshot from 2016-06-01 15 26 03](https://cloud.githubusercontent.com/assets/4616379/15711162/373a9e82-280d-11e6-9faf-780f97327fff.png)

It looks like the last driver isn't added to the fleet:
![screenshot from 2016-06-01 15 29 21](https://cloud.githubusercontent.com/assets/4616379/15711281/a9d2bb96-280d-11e6-86eb-d0b92d5f4c9a.png)
