### ISSUE TITLE
The orders view doesn't work correctly

### ISSUE THREAD

**Issue by Justinuz** [MelanieApplincourt/REPO_UZ_1234987#212]
To see the orders of the platform, I need to select the sender and after that, click on "My orders".
![capture d ecran 2016-06-01 a 17 25 38](https://cloud.githubusercontent.com/assets/18256571/15715298/36ed8b18-281e-11e6-84d0-9fa0c2a9014f.png)

I think it's better to see the orders directly.

**Comment by GuillaumeGolinvaux** [comment]
Ok
