### ISSUE TITLE
GPS Live tracking not working properly

### ISSUE THREAD

**Issue by icedfox** [MelanieApplincourt/REPO_UZ_1234987#218]
The messages are ignored due to a lack of privileges, but the events are received in the web app.

![screenshot from 2016-06-02 18 35 46](https://cloud.githubusercontent.com/assets/4616379/15752967/de5bcf4a-28f0-11e6-875d-253436cc3741.png)

**Comment by GuillaumeGolinvaux** [comment]
Ok
