### ISSUE TITLE
Extract of parcel can only be done for the current day

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#219]
It should be possible to select another day and extract for this day
- the extract should work for more then 1000 parcels (at the moment it does not go after 1000)

**Comment by Justinuz** [comment]
This is possible. You need the select a date in the search panel.
![capture d ecran 2016-06-03 a 09 05 52](https://cloud.githubusercontent.com/assets/18256571/15771372/83e26950-296a-11e6-96c3-708e36e6bf06.png)

For now, I set the limit to 5000 parcels.

**Comment by GuillaumeGolinvaux** [comment]
We can see the parcells on the 09/06 in this example, but when I do an extract, it gives me the extract of the 03/06

The parcells I want to extract (09/06)
![image](https://cloud.githubusercontent.com/assets/18420928/15772388/21db7ba0-2971-11e6-88bf-a2ef9b842b7e.png)

The extract (03/06):
![image](https://cloud.githubusercontent.com/assets/18420928/15772430/4e2d5444-2971-11e6-91c0-f9f1155a8d73.png)

**Comment by GuillaumeGolinvaux** [comment]
Ok, Happy Panda is Happy

![image](https://cloud.githubusercontent.com/assets/18420928/15772646/848594a6-2972-11e6-8d70-05f8e13dae76.png)
