### ISSUE TITLE
Issue adding a driver in a flow

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#223]
I add 2 driver on a flow and save. The save is done properly
![screen shot 2016-06-03 at 07 49 05](https://cloud.githubusercontent.com/assets/2649355/15769915/d0d0f822-295f-11e6-9060-6ba4b781aa5c.png)

When I come back on the page after refresh, the second driver has not been save properly.
![screen shot 2016-06-03 at 07 48 56](https://cloud.githubusercontent.com/assets/2649355/15769914/cf3f1dfe-295f-11e6-8160-3843bbfecb52.png)

**Comment by Justinuz** [comment]
I think you need to click on the "+" button before save

**Comment by MelanieApplincourt** [comment]
it is not user friendly then, is there something to do with that ?

**Comment by Justinuz** [comment]
![capture d ecran 2016-06-03 a 09 51 42](https://cloud.githubusercontent.com/assets/18256571/15772370/0ee23106-2971-11e6-9732-e3e93d483b4b.png)

**Comment by MelanieApplincourt** [comment]
OK
