### ISSUE TITLE
The tracking page does not work

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#226]
![screen shot 2016-06-03 at 12 02 49](https://cloud.githubusercontent.com/assets/2649355/15775619/221c6a68-2983-11e6-99de-abd10d11a68e.png)

**Comment by Justinuz** [comment]
![capture d ecran 2016-06-03 a 12 18 25](https://cloud.githubusercontent.com/assets/18256571/15784013/ea826282-29b0-11e6-91ca-134c268133bf.png)

**Comment by MelanieApplincourt** [comment]
1) On this parcel, the contact name is defined but I cannot see the ETA: https://web.integration.urbantz.com/#!/tracking/delivery?code=57516d572a134e1100eb4ccb

2) On the screen shot above why the address does not appear below the contact name?

**Comment by Justinuz** [comment]
Fixed
![capture d ecran 2016-06-06 a 11 32 48](https://cloud.githubusercontent.com/assets/18256571/15817873/6ec8d8e8-2bda-11e6-8d44-96c932d02fc6.png)

**Comment by Kgibaud** [comment]
The tracking page works correctly
