### ISSUE TITLE
Some consumer notifications are incorrect

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#227]
In a flow, when I activate the consumer notifications, I am asked to define the user, which has no sense:
![screen shot 2016-06-04 at 19 28 38](https://cloud.githubusercontent.com/assets/2649355/15801654/5273f374-2a9c-11e6-9a3a-50d88166a80b.png)

**Comment by GuillaumeGolinvaux** [comment]
Ok!
