### ISSUE TITLE
Wrong arrival time on the rounds/parcels list

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#229]
In this case I input a margin on the time slots. (platform Ecolotrans, 07/06)
![screen shot 2016-06-05 at 20 50 00](https://cloud.githubusercontent.com/assets/2649355/15807494/ed9e466a-2b5f-11e6-8a60-bf74bc0d0dd2.png)

**Comment by MelanieApplincourt** [comment]
Idem for directions
![screen shot 2016-06-05 at 20 58 59](https://cloud.githubusercontent.com/assets/2649355/15807512/597bc402-2b60-11e6-90d6-20dfe6dabb6a.png)

**Comment by GuillaumeGolinvaux** [comment]
Tested on 2 days on Ecolotrans Platform and 2 days in Regression Test Platform (Integration Environment), could not reproduce the issue.
