### ISSUE TITLE
Now, on parcel update on mobile the refresh of the dashboard shows a spinning wheel on blank page

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#231]
![screen shot 2016-06-05 at 21 11 59](https://cloud.githubusercontent.com/assets/2649355/15807580/23430736-2b62-11e6-87ef-08dc8176fbcc.png)

**Comment by MelanieApplincourt** [comment]
This blank screen with loader should not appear at all.

**Comment by GuillaumeGolinvaux** [comment]
OK!
