### ISSUE TITLE
Issue seing the parcels on the maps when delivery is on going

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#232]
Platform TGL / 05/6 / GreenHub 2, round 02 of David Melon.

The rounds is delivery ongoing but when I go to the round map I cannot see the parcels on the map, just the route...
![screen shot 2016-06-05 at 21 12 49](https://cloud.githubusercontent.com/assets/2649355/15807600/a22ae1c2-2b62-11e6-93cf-0d1118454f48.png)
![screen shot 2016-06-05 at 21 13 59](https://cloud.githubusercontent.com/assets/2649355/15807601/a45cfd40-2b62-11e6-8ce1-d24e6586717a.png)

**Comment by MelanieApplincourt** [comment]
![screen shot 2016-06-05 at 21 16 12](https://cloud.githubusercontent.com/assets/2649355/15807605/bde48030-2b62-11e6-9505-b60ecd083f79.png)

**Comment by MelanieApplincourt** [comment]
Moreover on this round, the score is 0%... It should be bigger

**Comment by MelanieApplincourt** [comment]
![screen shot 2016-06-06 at 11 35 26](https://cloud.githubusercontent.com/assets/2649355/15817937/d2138aa6-2bda-11e6-94d9-7575e1163bcb.png)

**Comment by MelanieApplincourt** [comment]
![screen shot 2016-06-06 at 11 36 05](https://cloud.githubusercontent.com/assets/2649355/15817944/e0ed58a4-2bda-11e6-83ab-ca0a5afaed2c.png)

**Comment by icedfox** [comment]
Should be fine now

**Comment by GuillaumeGolinvaux** [comment]
Ok
