### ISSUE TITLE
Notification "Edition finished successfully" in the round editor: Pop-up too big

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#238]
![screen shot 2016-06-07 at 11 27 12](https://cloud.githubusercontent.com/assets/2649355/15852938/50cb8812-2ca3-11e6-954b-ca05437ff24e.png)

**Comment by Kgibaud** [comment]
Pop-up ok : 

![image](https://cloud.githubusercontent.com/assets/19773079/15922181/bde7c710-2e26-11e6-9588-50584e8dd23e.png)
