### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#270]
The translation of the error messages on import must be done:
![screen shot 2016-06-19 at 15 47 14](https://cloud.githubusercontent.com/assets/2649355/16177705/21db0ffa-3635-11e6-9551-50e2e87e551f.png)
![screen shot 2016-06-19 at 15 46 23](https://cloud.githubusercontent.com/assets/2649355/16177706/23b16e3c-3635-11e6-8824-cd7976cefbd4.png)
![screen shot 2016-06-19 at 15 49 14](https://cloud.githubusercontent.com/assets/2649355/16177728/6760873a-3635-11e6-930e-c943e51e9d14.png)

**Comment by domitien** [comment]
Error message still in english in the test environment
![capture d ecran 2016-06-22 a 17 26 39](https://cloud.githubusercontent.com/assets/20042118/16273133/c65fce0e-38a0-11e6-9a1c-897fe7a414a2.png)

**Comment by domitien** [comment]
OK
