### ISSUE TITLE
Errors in optimisation: modal showing erros, date is not correct

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#271]
Platform regression test, imported file on 19/06 for parcels to be delivered on 19/06. when displaying the optim errors I see all errors on  17/06.
![screen shot 2016-06-19 at 12 43 11](https://cloud.githubusercontent.com/assets/2649355/16179684/7e5f0442-366d-11e6-9e02-36d8e076cdc7.png)

**Comment by GuillaumeGolinvaux** [comment]
Date ok.

However the hour does not seems to be correct:
![image](https://cloud.githubusercontent.com/assets/18420928/16271614/02df270e-389b-11e6-9e66-9d3d4ca8af54.png)

I imported the files at 4.32PM and launched the optim around 4.35PM. But the error shows 4.01PM

**Comment by GuillaumeGolinvaux** [comment]
Ok!
