### ISSUE TITLE
Edition of profile on mobile does not work

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#284]
On save the spinning wheel runs without ending and no save is done.

**Comment by GuillaumeGolinvaux** [comment]
Edition works on the Mobile App.

But when I look at the user's profile via the Web App, I don't see the modifications.

I changed the phone number of Drivertest and no change appears on the Web App

**Comment by GuillaumeGolinvaux** [comment]
Ok!
