### ISSUE TITLE
If there is no driver on a round, no possibility to edit

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#3]
![screen shot 2016-04-04 at 09 13 42](https://cloud.githubusercontent.com/assets/2649355/14240496/a0b451a0-fa45-11e5-873d-a76b961b7b88.png)

**Comment by Justinuz** [comment]
Fixed in dev.

**Comment by MelanieApplincourt** [comment]
OK
