### ISSUE TITLE
Rounds edition / add new parcel, select a flux does not set the default flux parameters

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#30]
I create a new parcels in the round editor.
I select a flux and I have a pop-up asking me if I want to "overwrite the parcel with the default configuration", I click on yes but the flux information (sender, hub, shift...) are not filled in.

**Comment by GuillaumeGolinvaux** [comment]
The default parameters of a parcel in the selected flux are now applied to the new parcel when selecting a flux
