### ISSUE TITLE
EDIT rounds / Delete rounds does no work

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#31]
In round edition, I delete a round, it disappears from the UI but no record appears in the log and it is not possible to save.
At the end the rounds are not deleted.

**Comment by MelanieApplincourt** [comment]
Oh bah la suppression de tournée ne fonctionne plus ...

**Comment by GuillaumeGolinvaux** [comment]
The rounds can be deleted and the parcels are put in "Geocoded" status
