### ISSUE TITLE
Delete announcement: log in the parcel details the stastus change

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#32]
At the moment , on delete a announcement file, the parcel is is the right status but the status change does not appear in the parcel status history: this change should be logged in the history also.

![screen shot 2016-04-13 at 10 33 47](https://cloud.githubusercontent.com/assets/2649355/14487507/3a382fb2-0163-11e6-927a-1ad73c87f02c.png)
![screen shot 2016-04-13 at 10 33 41](https://cloud.githubusercontent.com/assets/2649355/14487511/3d86a888-0163-11e6-9501-af3b061d7604.png)

**Comment by Justinuz** [comment]
DONE :+1:

**Comment by MelanieApplincourt** [comment]
OK
