### ISSUE TITLE
New round in rounds view

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#35]
When I add a round in the round view I should see the score % and service time, at the moment it is empty.
![screen shot 2016-04-13 at 18 37 30](https://cloud.githubusercontent.com/assets/2649355/14506942/991014c0-01c0-11e6-9f75-023174f41bda.png)

**Comment by Jon79** [comment]
Will only be resolved with vehicle routing
Le 13 avr. 2016 21:42, "MelanieApplincourt" notifications@github.com a
écrit :

**Comment by MelanieApplincourt** [comment]
OK :-)

**Comment by Jon79** [comment]
In the end I added this to the simple routing optimisation for the moment.

**Comment by MelanieApplincourt** [comment]
OK
