### ISSUE TITLE
Launch optim / optim launched even if there are exceptions

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#37]
I launch the optimisation with exception not resolved.
I receive the message that I have pending exception but the optim is launched. The optim should not run in this case.

![screen shot 2016-04-14 at 12 29 35](https://cloud.githubusercontent.com/assets/2649355/14525192/984b1e32-023c-11e6-8c32-6bc59ed79b2e.png)
![screen shot 2016-04-14 at 12 29 42](https://cloud.githubusercontent.com/assets/2649355/14525198/a0bb5ca8-023c-11e6-9855-f2bf6a9a4013.png)

**Comment by Justinuz** [comment]
DOOooOOOOOOoooooOOOOOone :)

**Comment by MelanieApplincourt** [comment]
oKKKKKKKKKKKK
