### ISSUE TITLE
When editing a round driver and vehicle should not be removed

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#4]
When clicking on Edit a round, the driver name and vehicle become empty. These fields should be displayed with their value.
![screen shot 2016-04-04 at 09 14 53](https://cloud.githubusercontent.com/assets/2649355/14240535/e5d93c46-fa45-11e5-9a3e-64c6cd07ca7e.png)

**Comment by Justinuz** [comment]
Fixed in dev.
