### ISSUE TITLE
Black overlay

### ISSUE THREAD

**Issue by GuillaumeGolinvaux** [MelanieApplincourt/REPO_UZ_1234987#41]
On both my tablet and PC (which are both on Windows OS, with latest version of Chrome) whenever I start using the web application I lose the branding at some point and all different platform are the same: black with no logo although the plateform settings are still well saved.

In the screenshot below, the plateform is supposed to be red with a Flash Transport logo on the top left

![image](https://cloud.githubusercontent.com/assets/18420928/14529939/0867f37e-0257-11e6-987f-73e6b3237a7c.png)

**Comment by MelanieApplincourt** [comment]
Because there is no platform by default.
