### ISSUE TITLE
As a driver I can see the sequence numbers of the parcels on the map

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#53]

**Comment by GuillaumeGolinvaux** [comment]
Ok.

**Comment by MelanieApplincourt** [comment]
NOK=> the sequence number on the screen is not correct, point 1 is displayed as point 2, on click on the point the number changes to 1 but it is written #2 ....

![screenshot_20160518-083049](https://cloud.githubusercontent.com/assets/2649355/15349455/401ccc18-1cd3-11e6-9393-0d5387a49dc9.png)

![screenshot_20160518-083055](https://cloud.githubusercontent.com/assets/2649355/15349459/47430e94-1cd3-11e6-97bb-6c92c9ad9a15.png)

**Comment by MelanieApplincourt** [comment]
AHHH, that's OK, this is due to the fact that several parcels are to be picked-up at the same address.
But the behavior is different from the web app. In the web app, the smallest number is shown on the map: 
![screen shot 2016-05-18 at 08 37 19](https://cloud.githubusercontent.com/assets/2649355/15349522/c2719edc-1cd3-11e6-9943-300b52d51aa1.png)

Is it possible to have the same for the mobile ? It would be more consistent...

**Comment by MelanieApplincourt** [comment]
Not fixed entirely but will be manage in a global user story later.
