### ISSUE TITLE
When there are no announcements, the loader does not stop

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#54]
In announcement menu, when there are no announcement, the loader runs with no end...
![screen shot 2016-04-16 at 16 45 12](https://cloud.githubusercontent.com/assets/2649355/14581668/a195cb88-03f2-11e6-9fe1-13b392c96ec6.png)

**Comment by Jon79** [comment]
Deployed to test

**Comment by MelanieApplincourt** [comment]
OK
