### ISSUE TITLE
After editing a round on the mobile app, it does not appear anymore in the web app

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#70]
I create a round, edit it in the mobile app but after save, this round does not appear in the barchart on the web app.

![screen shot 2016-04-19 at 23 36 16](https://cloud.githubusercontent.com/assets/2649355/14656408/affb6376-0687-11e6-8ae7-c7adf718f642.png)

**Comment by Justinuz** [comment]
The behavior was the same when you edit a round in the mobile app.

Done by Dani 👍

**Comment by MelanieApplincourt** [comment]
OK
