### ISSUE TITLE
Don't allow to launch an optim which is ongoing

### ISSUE THREAD

**Issue by Jon79** [MelanieApplincourt/REPO_UZ_1234987#73]

**Comment by Jon79** [comment]
Additionally, only allow to optimize if the previous optim is failed.

**Comment by MelanieApplincourt** [comment]
When optim is ongoing, show a small loader instead of the launching button. When the optim is done, have the possibility to relaunch the optim.

**Comment by Justinuz** [comment]
Done

**Comment by GuillaumeGolinvaux** [comment]
OK: I cannot click on Optimize anymore.
![image](https://cloud.githubusercontent.com/assets/18420928/15245058/b57f580e-1904-11e6-9014-576cc91350f4.png)
