### ISSUE TITLE
Provide feedback from the optim process in the announcement (schema)

### ISSUE THREAD

**Issue by Jon79** [MelanieApplincourt/REPO_UZ_1234987#74]

**Comment by Jon79** [comment]
Put ESRI warnings or NO_ROUTE error in the collection and show it in the announcement screen

**Comment by Justinuz** [comment]
Done for NO_ROUTE error.

**Comment by Justinuz** [comment]
DONE for ESRI errors

**Comment by MelanieApplincourt** [comment]
OK, but we will have to work on the error message...they are not user friendly :-)

**Comment by GuillaumeGolinvaux** [comment]
After the error message, when I go back to the announcement page, the optimization is "still running" and the "delete" or "optimize" buttons are not accessible ==> should reset the announcement options

![image](https://cloud.githubusercontent.com/assets/18420928/15352760/1933a7a8-1ce6-11e6-96dd-e2f6198869e8.png)

![image](https://cloud.githubusercontent.com/assets/18420928/15352747/09b89144-1ce6-11e6-9346-591f70b12484.png)

**Comment by Justinuz** [comment]
Fixed

**Comment by GuillaumeGolinvaux** [comment]
Ok!
