### ISSUE TITLE
Exception cannot be deleted

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#76]
When I import a file in Urbantz and the header are not recognised because the file has changed for instance or I import a wrong file, an exception is created with the header line but it cannot be removed or accepted.

![screen shot 2016-04-21 at 13 02 53](https://cloud.githubusercontent.com/assets/2649355/14708033/62b700a6-07c8-11e6-844e-b4ea88ef480d.png)

**Comment by Justinuz** [comment]
Done :)

**Comment by MelanieApplincourt** [comment]
OK
