### ISSUE TITLE
TEST / Cannot save a round where I moved the parcels

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#82]
I take a round with specific time slot, I change the order of parcel, activate sequence optimisation and save. I receive an error:
![screen shot 2016-04-22 at 19 20 43](https://cloud.githubusercontent.com/assets/2649355/14749431/9cf9b2f2-08bf-11e6-89bd-95d4b7fe7cfb.png)

**Comment by Justinuz** [comment]
I can't reproduce this bug.

**Comment by ventur** [comment]
I tried too but I can't reproduce neither

**Comment by MelanieApplincourt** [comment]
Go to platform regression test - 28/04/16 move Parcels and save:
![screen shot 2016-04-25 at 20 49 06](https://cloud.githubusercontent.com/assets/2649355/14795092/303d93a8-0b27-11e6-8bef-dd82a2ea3f4d.png)

**Comment by MelanieApplincourt** [comment]
OK
