### ISSUE TITLE
TEST / Dashboard, rounds in list view missing vehicle info

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#83]
In the dashboard, display the rounds in list format, the vehicle name should appear:
![screen shot 2016-04-22 at 19 24 12](https://cloud.githubusercontent.com/assets/2649355/14749493/fee1ea16-08bf-11e6-80d7-ecbb293e3d5c.png)

**Comment by Justinuz** [comment]
Done

**Comment by MelanieApplincourt** [comment]
OK
