### ISSUE TITLE
Round edition add check box in the orphan parcels adding

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#84]
Add the same checkboxes than on the parcels lis of a rounds when i go the the orphan parcels page.
The principle should be the same than on the rounds parcels list view with drag and drop instead of click on "+".

**Comment by MelanieApplincourt** [comment]
It seems that it does not work correctly:
When I have orphan parcels, I click on "orphans" on the left but no parcel appears in the list on the right.
![screen shot 2016-05-10 at 15 56 49](https://cloud.githubusercontent.com/assets/2649355/15171446/ebcdcd62-174e-11e6-9bd1-1f3f3591c0e8.png)

**Comment by Justinuz** [comment]
What platform ? And what date ?

I have this on Regression test for today.

![capture d ecran 2016-05-17 a 09 33 18](https://cloud.githubusercontent.com/assets/18256571/15314501/87ad940c-1c12-11e6-8961-59b4deb892a6.png)

**Comment by GuillaumeGolinvaux** [comment]
I tested the Round Editor this afternoon (Regression Test, Test Server) and the Orphan system worked fine.
Melanie, I redirect this to you if you have other comments: maybe a use case I did not test?

**Comment by MelanieApplincourt** [comment]
OK
