### ISSUE TITLE
TEST / Add new parcel / cannot input a time slot for delivery

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#86]
When I create a parcel I cannot save the new parcel if I input a time slot different from the shift, if I save I receive an error message "The value you provided is invalid."

![screen shot 2016-04-24 at 17 27 51](https://cloud.githubusercontent.com/assets/2649355/14768429/37ceab56-0a42-11e6-989c-26bc505b7f32.png)

**Comment by ventur** [comment]
What is the behaviour expected? The parcel can be included in every time window even if it is not included in the shift? Please specify the functionality.

**Comment by MelanieApplincourt** [comment]
ok
