### ISSUE TITLE
As a dispatcher I can enter manually a barcode if the scan does not work properly

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#90]
In the dispatcher app / scanning, as a dispatcher, I can enter manually a barcode to get the round and sequence number and change the status of the parcel like a scan.

**Comment by icedfox** [comment]
Also valid for drivers

**Comment by GuillaumeGolinvaux** [comment]
Tested with the following parcel on regression test:
![screenshot_2016-05-13-12-09-28 1](https://cloud.githubusercontent.com/assets/18420928/15244881/b70a6750-1903-11e6-9136-cb58f3eae1fb.jpg)
