### ISSUE TITLE
As a PM If the data I import in urbantz contains erros I receive details about the errors

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#91]
For instance:
- wrong file format (if file imported manually or by FTP)
- Wrong value provided for data "XXX"
- delivery date int he past or more than 1 week in the future
- number of columns is correct
- if client used in the imported file, the client name exist in the application

In addition: ensure we can retrieve easily the file imported by the user.

**Comment by Jon79** [comment]
Move file parser handling to the server side and store in S3 for archiving purposes.

**Comment by Justinuz** [comment]
Done in dev.

**Comment by Justinuz** [comment]
Done in test on the branch "announcement-1.1.3"

**Comment by MelanieApplincourt** [comment]
Issue with the validations:
I try to import a file where e sender in the file has not been created. In this case I would expect the user to receive a message in a modal box in the UI. At the moment, nothing happens and I can see the following info in the logs:
![screen shot 2016-06-16 at 20 56 56](https://cloud.githubusercontent.com/assets/2649355/16129667/ef4599d8-3405-11e6-91e4-fb4ceff525c9.png)

Idem for parcel imported in the past, I receive no feedback in the UI but this message in the logs:
![screen shot 2016-06-16 at 21 04 55](https://cloud.githubusercontent.com/assets/2649355/16129676/0254a12c-3406-11e6-90d3-7051b6cf440d.png)

**Comment by MelanieApplincourt** [comment]
Validations work well now but i found another issue:

TGL import a file from colis prive with no headers, in this case even if the file is correct I always receive the error message saying the number of columns is not correct. It should not give this error.

**Comment by GuillaumeGolinvaux** [comment]
Problem with the date format: I insert "abc" in the date field, and instead of getting an error related to the date, I get the standard error message. (verify the content of your file...)
![image](https://cloud.githubusercontent.com/assets/18420928/16334143/904f3a4c-39ff-11e6-8d84-64f168370c6e.png)

**Comment by GuillaumeGolinvaux** [comment]
For the hour format, if I enter incorrect data (for example "abc"), I have no error message, the parcel is geocoded but with the standard hour of the flow:
![image](https://cloud.githubusercontent.com/assets/18420928/16334432/345ff06c-3a01-11e6-8acd-0bdef97a83d8.png)
In this case, the value "abc" became 7AM without warning message.

**Comment by GuillaumeGolinvaux** [comment]
Rest works fine!

**Comment by MelanieApplincourt** [comment]
OK
