### ISSUE TITLE
Real time update of statut change does not work anymore

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#94]
I go to the dashboard / hub view, bar chart and I scan parcel to go to from awaiting to arrival to pending delivery, the status does not change directly on the mane while scanning.
When I go bak to the hub and refresh I can see that the statuses have changed.

**Comment by MelanieApplincourt** [comment]
Sorry, I confirm (and Justin is now my witness) that it does not work

**Comment by ventur** [comment]
I believe you :) Do you know if always you had this problem you were logged, you logged out and logged with another user and you didn't change the selected platform? That's the only case were I could reproduce the issue and I fixed. 
I assign again the label to be tested and if you find again the issue I'll try to find another solution or see how to replicate it or jump over the window

**Comment by MelanieApplincourt** [comment]
As i am not able to replicate at the moment I give up but If I find a way to reproduce you'll hear again about this issue ;-)
