### ISSUE TITLE
Driver App: exception in delivery confirmation

### ISSUE THREAD

**Issue by GuillaumeGolinvaux** [MelanieApplincourt/REPO_UZ_1234987#99]
![screenshot_2016-04-25-14-39-35 1](https://cloud.githubusercontent.com/assets/18420928/14784009/9d42a86e-0af3-11e6-8ae1-3871d91917f7.jpg)

In the middle of a round, the adress is geocoded and the driver has the parcel, but when clicking on "deliver the parcel", I am stuck with that screen and cannot either confirm the delivery or set it as failed.

**Comment by MelanieApplincourt** [comment]
We cannot reproduce, so it will be closed for the moment
